/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tortilleriapresentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author MoriTejo
 */
public class PantallaMetodoPago extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMetodoPago
     * @param mediador
     */
    public ControlPresentacionVenta mediador;

    public PantallaMetodoPago(ControlPresentacionVenta mediador) {
        initComponents();
        this.mediador = mediador;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmarPago = new javax.swing.JButton();
        comboBoxMetodo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConfirmarPago.setText("COntinuar");
        btnConfirmarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPagoActionPerformed(evt);
            }
        });

        comboBoxMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta debito", "Tarjeta credito" }));
        comboBoxMetodo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                comboBoxMetodoInputMethodTextChanged(evt);
            }
        });
        comboBoxMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMetodoActionPerformed(evt);
            }
        });

        jLabel1.setText("Metodo de pago");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnConfirmarPago))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(btnConfirmarPago)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPagoActionPerformed
        try {
            String metodoPago = comboBoxMetodo.getSelectedItem().toString();
            double dineroRecibido = 0.0;
            
            if (metodoPago.equalsIgnoreCase("Efectivo")) {
                String input = JOptionPane.showInputDialog(this, "¿De cuánto es el billete recibido? \n Total a cobrar: $" + mediador.getTotalActual());
                if (input == null || input.trim().isEmpty()) {
                    return; 
                }
                dineroRecibido = Double.parseDouble(input);
            } else {
                dineroRecibido = mediador.getTotalActual();
            }
            mediador.solicitarCobro(dineroRecibido, metodoPago, this);
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Monto inválido.");
        }
    }//GEN-LAST:event_btnConfirmarPagoActionPerformed

    private void comboBoxMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMetodoActionPerformed

    private void comboBoxMetodoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_comboBoxMetodoInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMetodoInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarPago;
    private javax.swing.JComboBox<String> comboBoxMetodo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
